### PR TITLE
OCPBUGS-8068: Fix for node's last_error disappears briefly on cleaning failure

### PR DESCRIPTION
**Pull request by elfosardo**
Also fix oslo-messaging dependency

### CODE REVIEW

**Comment by derekhiggins** [comment]
/test prevalidation-e2e-metal-ipi-bm-prevalidation

Of the 8 failures for this job so far
3 x rpm's not synced to prevalidation lab yet
3 x lab dhcp problem (now fixed)
2 x bootstrap errors with different error messages, 

retesting to see if either of the bootstrapping issues reproduces so we know which one to look into

**Comment by elfosardo** [comment]
/test prevalidation-e2e-metal-ipi-virtualmedia-prevalidation
the fix should be merged, retesting

**Comment by elfosardo** [comment]
/override ci/prow/prevalidation-e2e-metal-ipi-bm-prevalidation

**Pull request merged**
