### PR TITLE
Build container from rhel7

### PR DESCRIPTION
**Pull request by elfosardo**
Change base image from centos7 to rhel7 for ocp container

### CODE REVIEW

**Comment by dhellmann** [comment]
When would we update this to RHEL8?

**Comment by elfosardo** [comment]
@dhellmann apparently there are no builders for rhel8 at the moment and there's no ETA to have that for now

**Comment by dhellmann** [comment]
@elfosardo ok, if we can't yet then we'll just keep that as a todo item

**Comment by hardys** [comment]
Yeah IMO we should definitely avoid doing anything in the short-medium term which deviates significantly from our current test matrix, which is pretty much all centos7 (so rhel7 should work fine, modulo any dependency issues etc)

**Pull request merged**
