### PR TITLE
Copy iPXE binaries to /shared at runtime

### LINKED ISSUE #42: cp error when starting dnsmasq
There is an error copying a pxe file on startup, in my environment dnsmasq starts, and deployment still works fine but we should probably review the files copied to ensure we have the expected files for vm/baremetal environments;

```
[core@localhost ~]$ sudo podman logs dnsmasq
cp: cannot stat '/usr/share/ipxe/ipxe.efi': No such file or directory
dnsmasq: started, version 2.79 DNS disabled
dnsmasq: compile time options: IPv6 GNU-getopt DBus no-i18n IDN2 DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth DNSSEC loop-detect inotify
dnsmasq-dhcp: DHCP, IP range 172.22.0.10 -- 172.22.0.100, lease time 1h
dnsmasq-dhcp: 
dnsmasq-tftp: TFTP root is /shared/tftpboot 
dnsmasq-dhcp: DHCPDISCOVER(ens4) 00:c8:ff:b6:7b:04 
dnsmasq-dhcp: DHCPOFFER(ens4) 172.22.0.72 00:c8:ff:b6:7b:04 

```

The copy happens here: 

https://github.com/openshift/ironic-image/blob/master/rundnsmasq.sh#L22

Looking inside the container we can see these files:

```
[root@localhost /]# ls /usr/share/ip<tab>
ipmitool/ ipxe/     ipxe.efi/ 
[root@localhost /]# ls /usr/share/ipxe
10222000.rom  10ec8139.rom  1af41000.rom  808610d3.rom	ipxe-i386.efi	 ipxe.dsk  ipxe.lkrn  undionly.kpxe
10ec8029.rom  15ad07b0.rom  8086100e.rom  80861209.rom	ipxe-x86_64.efi  ipxe.iso  ipxe.usb
[root@localhost /]# ls /usr/share/ipxe.efi/
10222000.rom  10ec8029.rom  10ec8139.rom  15ad07b0.rom  1af41000.rom  8086100e.rom  808610d3.rom  80861209.rom
```

I'm not certain atm if we can just remove the copy of ipxe.efi, or if we need to rename ipxe-x86_64.efi which does exist

### PR DESCRIPTION
**Pull request by derekhiggins**
We can't copy these files here at build time as the shared volume
doesn't exist. We were attempting to do this in two places and only
one of them worked(partially).

Fixes #42

### CODE REVIEW

**Comment by juliakreger** [comment]
@derekhiggins @elfosardo Is this change still required? looks like it needs to be rebased?

**Comment by derekhiggins** [comment]
> @derekhiggins @elfosardo Is this change still required? looks like it needs to be rebased?

I've rebased it, but I don't know if its still required, the bug it was fixing may have been fixed here
https://github.com/openshift/ironic-image/pull/45/commits/0b4b7dfb773593be72b883bb78c1d900356b8a84 
but its a good simplification anyways as we will no longer be moving files around twice.

**Comment by elfosardo** [comment]
@derekhiggins if this is still valid, you'll have to create a bug in Bugzilla to validate it, change the title here to connect the PR to the bug, then run `/bugzilla refresh`, otherwise the tide check won't be validated

**Comment by stbenjam** [comment]
This seems different than how metal3/ironic-image is doing things, could we get this approach there first and then bring it into dowstream? I don't think code should land in openshift first.

**Comment by derekhiggins** [comment]
> This seems different than how metal3/ironic-image is doing things, could we get this approach there first and then bring it into dowstream? I don't think code should land in openshift first.

I'm not sure this is relevant upstream, here we are using a packaged ipxe file, upstream we are building it. Actually this patch bings the two closer in that it gets ride of prepare-ipxe.sh.

**Comment by stbenjam** [comment]
Got it, thanks, I understand now -- is `/usr/share/ipxe/ipxe.efi` the 32-bit binary? Do we really ever plan to have that?

**Comment by derekhiggins** [comment]
> Got it, thanks, I understand now -- is `/usr/share/ipxe/ipxe.efi` the 32-bit binary? Do we really ever plan to have that?

I believe the origins of referencing two possible paths we're originally to support multiple base distros(Centos and RHEL, 7 and 8, where the patsh changed on different base images), eventually (maybe even now?) we could get rid of it altogether.

**Comment by stbenjam** [comment]
This change looks good, I'll update it to include snponly.efi when it's part of the ipxe-bootimgs package.

**Comment by stbenjam** [comment]
/retitle Bug 1810071: Copy iPXE binaries to /shared at runtime

**Pull request merged**
