### PR TITLE
OCPBUGS-31830,OCPBUGS-31686: Update packages in 4.15

### PR DESCRIPTION
**Pull request by iurygregory**
This includes a fix for bugs: OCPBUGS-31830 and OCPBUGS-31686

### CODE REVIEW

**Comment by elfosardo** [comment]
https://github.com/openshift/ironic-image/pull/470 takes precedence and includes the fix

**Comment by dtantsur** [comment]
/close

Superseded by https://github.com/openshift/ironic-image/pull/470

**Pull request closed without merging**
