### PR TITLE
Bring Ironic version to 18.3.0-0.20211206200515.0ff3da2

### PR DESCRIPTION
**Pull request by rhjanders**
This commit pulls in the latest ironic-master into OpenShift, 
bringing a number of bugfixes and enhancements.

### CODE REVIEW

**Comment by elfosardo** [comment]
after talking with Jacob, we've decided to try and get this merged before next upstream releases are ready

**Review by elfosardo — APPROVED** [review]

**Comment by elfosardo** [comment]
tagged in production, waiting for the sync

**Comment by rhjanders** [comment]
Changed the title and description to better reflect the current course of action. While this PR was originally opened to incorporate https://review.opendev.org/c/openstack/ironic/+/817154 in ironic-image for our Fujitsu colleagues, we ended up syncing all the latest changes to Ironic master into openshift/ironic-image.

**Pull request merged**
