### PR TITLE
NO-ISSUE: Sync with metal3 upstream 2024-12-16

### PR DESCRIPTION
**Pull request by elfosardo**

### CODE REVIEW

**Comment by derekhiggins** [comment]
CI failures look related (./metal3-ramdisk-logs/metal3-ramdisk-logs/logs/current.log)
`2024-12-18T00:38:37.537044355Z /bin/runlogwatch.sh: line 6: inotifywait: command not found`

**Comment by iurygregory** [comment]
Did we change something that removed inotifywait ? O.o

**Comment by derekhiggins** [comment]
> Did we change something that removed inotifywait ? O.o

No, it wasn't being used upto now

**Comment by iurygregory** [comment]
weird, all BMH are provisioned in the vmedia at least, will recheck

**Comment by derekhiggins** [comment]
/retest-required
all three ipi jobs times out after 4 hours, most of the time was taken up by the building of the ironic image e.g.

`INFO[2024-12-18T20:36:37Z] Build ironic-amd64 succeeded after 1h33m52s  
`

**Pull request merged**
