### PR TITLE
Image sync

### PR DESCRIPTION
**Pull request by derekhiggins**
Sync patches from upstream

### CODE REVIEW

**Comment by derekhiggins** [comment]
Anybody know if there is a reason we never pulled in https://github.com/metal3-io/ironic-image/commit/637118160c83370a5857a73067feadc048b49586 ?

**Comment by elfosardo** [comment]
/hold
the prevalidation jobs are not working as intended
we need at least https://github.com/openshift/release/pull/15891 for ironic images

**Pull request merged**
