### PR TITLE
Remove custom healthchecks

### PR DESCRIPTION
**Pull request by dtantsur**
Health checking from inside the container has a limited use, and
the way we're doing it now doesn't work without built-in DHCP.
Removing it to solve the immediate problem while we're working
on proper health checks.

Conflicts:
	Dockerfile
	rundnsmasq.sh
	runhttpd.sh

### CODE REVIEW

**Comment by dtantsur** [comment]
```
STEP 9: COPY --from=builder /tmp/esp.img /httpboot/uefi_esp.img
error: build error: error building at STEP "COPY --from=bu...5efcb2350c80/merged/tmp/esp.img": no such file or directory
```
Huh?

**Comment by stbenjam** [comment]
> ```
> STEP 9: COPY --from=builder /tmp/esp.img /httpboot/uefi_esp.img
> error: build error: error building at STEP "COPY --from=bu...5efcb2350c80/merged/tmp/esp.img": no such file or directory
> ```
> 
> Huh?

Seems like something failed with /tmp/esp.img but I can't see why earlier in the logs :-(

**Pull request merged**
