### PR TITLE
bug 1833385: Allows users to configure any non-link-local IPV6 address for the provisioning interface

### PR DESCRIPTION
**Pull request by mvazquezc**
This fix introduces the fix created for metal3-io ironic-image https://github.com/metal3-io/ironic-image/pull/156/

Thanks @maelk for fixing our previous fix!

### CODE REVIEW

**Comment by jparrill** [comment]
This is the upstream PR already merged: https://github.com/metal3-io/ironic-image/pull/153

**Comment by russellb** [comment]
/hold

Can you go ahead and file a 4.5 bz for this?

**Comment by russellb** [comment]
/hold cancel

don't need the hold, prow is already waiting for the `bugzilla/valid-bug` label

**Comment by jparrill** [comment]
/retitle bug 1833385: Allows users to configure any non-link-local IPV6 address for the provisioning interface

**Pull request merged**
