### PR TITLE
OCPBUGS-19019: Switch from current-tripleo to puppet-passed-ci

### PR DESCRIPTION
**Pull request by derekhiggins**
current-triple is no longer maintained and doesn't contain recent fixes we require.

### CODE REVIEW

**Comment by LorbusChris** [comment]
While we're at it, let's make the same change in Dockerfile.fcos (https://github.com/openshift/ironic-image/blob/master/Dockerfile.fcos#L20)

**Comment by LorbusChris** [comment]
This change should also let us drop the line that installs python

**Comment by derekhiggins** [comment]
> While we're at it, let's make the same change in Dockerfile.fcos (https://github.com/openshift/ironic-image/blob/master/Dockerfile.fcos#L20)

Done, which begs the question of why the fcos image us using centos...
> FROM quay.io/centos/centos:stream9

A fix for another PR?

**Comment by LorbusChris** [comment]
> Done, which begs the question of why the fcos image us using centos... (look at the second FROM)
> 
> > FROM quay.io/centos/centos:stream9
> 
> A fix for another PR?

@derekhiggins I totally missed that question. The Fedora specific part is really just the first stage and using C9S in the second is actually intended. In builds done outside of Prow (via https://github.com/okd-project/okd-payload-pipeline), that is the common base for payload images, so some space is theoretically saved there due to deduplication. Arguably though we do not get that benefit currently from our official Prow builds with its UBI-derived base.

**Pull request merged**
