### PR TITLE
Fix binary location

### PR DESCRIPTION
**Pull request by e-minguez**
```
/usr/bin/gunicorn-3
/usr/bin/gunicorn-3.6
/usr/bin/gunicorn_paster-3
/usr/bin/gunicorn_paster-3.6
/usr/bin/python3-gunicorn
/usr/bin/python3-gunicorn_paster
```

### CODE REVIEW

**Comment by iurygregory** [comment]
/retest
/approve

I will wait to see if e2e-metal-ipi-virtualmedia goes green =)

**Review by iurygregory — APPROVED** [review]

**Comment by elfosardo** [comment]
do we need the same change upstream (metal3-io) ?

**Comment by iurygregory** [comment]
@elfosardo I think we need

**Comment by e-minguez** [comment]
It seems the CentOS version contains the 'gunicorn' binary where the RHEL one doesn't:


python3-gunicorn from CentOS is version 20.4 and it has:

```
-rwxr-xr-x. 1 root root  390 Jan 29  2020 /usr/bin/gunicorn
lrwxrwxrwx. 1 root root   17 Jan 29  2020 /usr/bin/gunicorn-3 -> /usr/bin/gunicorn
lrwxrwxrwx. 1 root root   17 Jan 29  2020 /usr/bin/gunicorn-3.6 -> /usr/bin/gunicorn
```

python3-gunicorn from RHEL8 is version 19.9 and it has:
```
-rwxr-xr-x. 1 root root 402 Oct  1  2019 /usr/bin/gunicorn-3
lrwxrwxrwx. 1 root root  19 Oct  1  2019 /usr/bin/gunicorn-3.6 -> /usr/bin/gunicorn-3
```

I've created a BZ requesting bumping the python3-gunicorn version in RHEL https://bugzilla.redhat.com/show_bug.cgi?id=1976117

**Comment by elfosardo** [comment]
@e-minguez is this still needed?

**Comment by e-minguez** [comment]
> @e-minguez is this still needed?

TBH I don't know. I'm on parental leave currently so no idea 😅

**Pull request closed without merging**
