### PR TITLE
Update dependencies for OCP 4.12

### PR DESCRIPTION
**Pull request by elfosardo**

### CODE REVIEW

**Comment by elfosardo** [comment]
/hold
we may need to wait for more packages to be updated

**Comment by elfosardo** [comment]
/unhold
looks good

**Comment by elfosardo** [comment]
let's wait for https://github.com/openshift/ironic-agent-image/pull/60 to pass before moving forward with new tags in production

**Comment by dtantsur** [comment]
/lgtm

Also closes https://bugzilla.redhat.com/show_bug.cgi?id=2104275

**Comment by elfosardo** [comment]
/unhold
errors in https://github.com/openshift/ironic-agent-image/pull/60 are not due to the packages change

**Review by iurygregory — APPROVED** [review]

**Pull request merged**
