### PR TITLE
Bug 2023748: Compare IPs using the short form of IPv6 address

### PR DESCRIPTION
**Pull request by bfournie**
This is a backport of https://github.com/openshift/ironic-image/pull/220 to 4.9.

### CODE REVIEW

**Comment by derekhiggins** [comment]
lgtm, is there a bug in 4.9 for it?

**Comment by bfournie** [comment]
> lgtm, is there a bug in 4.9 for it?

Yes, https://bugzilla.redhat.com/show_bug.cgi?id=2023748

**Review by awolffredhat — APPROVED** [review]

**Comment by hardys** [comment]
I've been discussing getting the QE team permissions added to approve, but since that's still ongoing I'll approve this

**Pull request merged**
