### PR TITLE
Wait for provisioning interface and db sync

### PR DESCRIPTION
**Pull request by hardys**
Cherry-picks of the following upstream PRs

https://github.com/metal3-io/ironic-image/pull/88

https://github.com/metal3-io/ironic-image/pull/89

### CODE REVIEW

**Comment by russellb** [comment]
Image build in CI failed on:

`No package python3-PyMySQL available.`

**Comment by russellb** [comment]
Based on the build log, it looks like it's building with el7 rpms, but Dockerfile.ocp has python3-PyMySQL assuming el8.

**Comment by hardys** [comment]
Thanks to @stbenjam for pointing out https://github.com/openshift/images/pull/11 which may be the root cause of the CI failure, e.g some errors from yum have been ignored but now cause failure.

I pushed https://github.com/metal3-io/ironic-image/pull/90 and added the same commit here to see if that is sufficient to resolve the build issue, marked this WIP until that is confirmed

**Comment by elfosardo** [comment]
we can remove the WIP, verified the correct package is installed
the name is python-PyMySQL and it's installed as oslo-db dependency

**Pull request merged**
