### PR TITLE
METAL-804: Bump ironic hash to include recent fixes and features

### PR DESCRIPTION
**Pull request by elfosardo**
This adds the redfish implementation of attach/detach generic iso.

### CODE REVIEW

**Comment by lhh** [comment]
Looks like the package hadn't appeared in the repos; rerunning tests

**Comment by elfosardo** [comment]
I can see from the logs that the cluster does get initialized so I'm going to override the virtualmedia prevalidation test
the rest looks good, just waiting for the sushy package to be  synced to production

**Comment by elfosardo** [comment]
/override ci/prow/prevalidation-e2e-metal-ipi-virtualmedia-prevalidation

**Pull request merged**
