### PR TITLE
Bug 1917937: Force rebuild to pick up latest dnsmasq

### PR DESCRIPTION
**Pull request by elfosardo**
We force a rebuild to grab the new dnsmasq pkg required to fix
the security vulnerability described in
https://access.redhat.com/security/vulnerabilities/RHSB-2021-001

### CODE REVIEW

**Comment by elfosardo** [comment]
correct version installed
 dnsmasq                              x86_64  2.79-11.el8_2.2                             rhel-8-appstream              318 k

**Review by dtantsur — APPROVED** [review]
/lgtm

**Comment by crawford** [comment]
Can you help me understand what I'm looking at here? This makes it seem as if dnsmasq and other dependencies aren't pinned to a specific version and rely on the time of build.

**Comment by elfosardo** [comment]
@crawford that's exactly it, the new dnsmasw package is in repository, we need a dummy PR (with a temporal mark) to rebuild the image and promote it with the new package. Thanks!

**Pull request merged**
