### PR TITLE
Improve resiliency of eTag handling

### PR DESCRIPTION
**Pull request by rhjanders**
This commit brings the upstream OpenStack/Sushy fixes improving eTag handling into OpenShift 4.13

### CODE REVIEW

**Comment by elfosardo** [comment]
/hold
seems we're missing some CI config stuff

**Comment by elfosardo** [comment]
this should fix the missing stuff https://github.com/openshift/release/pull/33851

**Comment by rhjanders** [comment]
/close
As per https://github.com/openshift/ironic-image/pull/311#issuecomment-1307355069.
Thank you Riccardo!

**Comment by rhjanders** [comment]
New PR: https://github.com/openshift/ironic-image/pull/313

**Pull request closed without merging**
