### PR TITLE
Rename packages list

### PR DESCRIPTION
**Pull request by elfosardo**
Use .ocp extension to be explicit on the purpose

### CODE REVIEW

**Comment by dtantsur** [comment]
Why are you doing this? This change adds an unnecessary divergence from upstream.

**Comment by elfosardo** [comment]
> Why are you doing this? This change adds an unnecessary divergence from upstream.

I'm doing it exactly because of that, to indicate that this is different from upstream

**Review by bfournie — APPROVED** [review]

**Pull request merged**
