### PR TITLE
Bug 1906397: Fix incorrect IPA option

### PR DESCRIPTION
**Pull request by dtantsur**
This issue managed to sneak in during the last rebase.

Upstream: https://github.com/metal3-io/ironic-image/pull/232

### CODE REVIEW

**Review by bfournie — APPROVED** [review]

**Comment by stbenjam** [comment]
This needs a BZ after feature freeze

**Comment by dtantsur** [comment]
> This needs a BZ after feature freeze

Can we maybe not overdo it with formalities for a trivial regression?

**Comment by stbenjam** [comment]
> > This needs a BZ after feature freeze
> 
> Can we maybe not overdo it with formalities for a trivial regression?

If it's after FF, it needs a bug. I'm just the messenger. The bots will be enforcing it shortly, anyway.

**Comment by dtantsur** [comment]
> The bots will be enforcing it shortly, anyway.

Well, there aren't now, so you're enforcing it, tripling my work to fix a trivial thing...

**Comment by stbenjam** [comment]
/shrug

It takes a few minutes to a file a BZ once you know where to do it. Just do the right thing.

**Comment by dtantsur** [comment]
Okay, I'll wait for someone to actually hit it and report a bugzilla.

Also, what is wrong with the CI now?

**Comment by stbenjam** [comment]
/retitle Bug 1906397: Fix incorrect IPA option

**Comment by stbenjam** [comment]
/lgtm

Feel free to remove the hold (`/` `hold cancel`) when CI is fixed.

**Pull request merged**
