### PR TITLE
Enable irmc bios interface

### PR DESCRIPTION
**Pull request by hs0210**
I will pick up the upstream PRs after that has been merged, and will add that commits into this one.
URL of upstream PRs are as follows.
- https://github.com/metal3-io/ironic-image/pull/286
- https://github.com/openshift/ironic-image/pull/190

Therefore, please pend the review of this PR.

Signed-off-by: Hu Shuai <hus.fnst@cn.fujitsu.com>

### CODE REVIEW

**Comment by elfosardo** [comment]
I think we should also wait for https://github.com/openshift/ironic-image/pull/190 to avoid more conflicts/rebase

**Comment by hs0210** [comment]
@elfosardo Thanks, done.

**Comment by dtantsur** [comment]
/hold

We should wait until https://github.com/metal3-io/ironic-image/pull/286 merges or at least is ready to review and passes the CI.

**Review by elfosardo — CHANGES_REQUESTED** [review]
@hs0210 my understanding is that this works if python-scciclient is at least version 0.10.0, as specified in the upstream change https://github.com/metal3-io/ironic-image/pull/286
you need to update the main-packages file to reflect that

**Comment by hs0210** [comment]
@elfosardo Done.

**Comment by elfosardo** [comment]
@hs0210 thanks, the failure at this moment is normal, we need to add the package
I'll take care of retesting this once the pkg is in the correct repo

**Comment by elfosardo** [comment]
@hs0210 had to change version to the correct one as we track directly master

**Comment by hase1128** [comment]
@elfosardo 

> I'll take care of retesting this once the pkg is in the correct repo

Thank you.
I don't know how to check the status of pkg and repository of python-scciclient, but if the latest rpm(0.10.0) is put in the repo, I think that rpm will be used. Could you please check the pkg in the repo?

**Comment by elfosardo** [comment]
@hase1128 the version that I specified includes the required change

**Comment by hase1128** [comment]
@elfosardo, @rhjanders 

Regarding CI error, does this mean we still can't get the correct pkg(0.9.1-0.20210720102209.34ccd96.el8)?

--------------------------------------
Error: Failed to download metadata for repo 'localdev-rhel-8-server-ose-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Ignoring repositories: localdev-openstack-16-for-rhel-8-rpms, localdev-rhel-8-appstream-rpms, localdev-rhel-8-baseos-rpms, localdev-rhel-8-codeready-builder-rpms, localdev-rhel-8-fast-datapath-rpms, localdev-rhel-8-rt-rpms, localdev-rhel-8-server-ansible-2.9-rpms, localdev-rhel-8-server-ose-rpms
Last metadata expiration check: 0:00:19 ago on Tue Jul 20 12:43:17 2021.
No match for argument: python3-scciclient >= 0.9.1-0.20210720102209.34ccd96.el8
Error: Unable to find a match: python3-scciclient >= 0.9.1-0.20210720102209.34ccd96.el8
--------------------------------------

**Comment by rhjanders** [comment]
@hase1128 this looks more like a repo server issue (possibly due to metadata being re-generated while the job ran). Let me see if I can rerun the tests.

**Comment by elfosardo** [comment]
@hase1128 @rhjanders the repo sync from production can take quite some time and I would really like to see #190 to merge first to avoid more rebases. I'll take care of retesting this later.

**Comment by elfosardo** [comment]
| /test e2e-metal-ipi
-- | --

**Review by elfosardo — APPROVED** [review]
we can merge this even if it now fails for some reason, it was passing before the rebase and the rebase does not influence the CI jobs

**Comment by elfosardo** [comment]
I triggered the prevalidation jobs again although they're failing because some new packages have been tagged in the prevalidation repositories and they're missing correct dependencies. This won't influence production and the failure is not due to this PR, the main CI jobs are passing correctly.
To avoid delaying further this PR, I'm going to bypass the failing prevalidation jobs and merge the change.

**Comment by elfosardo** [comment]
/override ci/prow/prevalidation-e2e-metal-ipi-virtualmedia-prevalidation

**Pull request merged**
