### PR TITLE
Create EFI esp.img on aarch64

### PR DESCRIPTION
**Pull request by yselkowitz**
Please check that this makes sense for aarch64.

/cc ﻿@jeremyfreudberg
/cc @elfosardo

### CODE REVIEW

**Comment by dtantsur** [comment]
Makes sense, but you could you also propose your change upstream to https://github.com/metal3-io/ironic-image/blob/master/Dockerfile#L20? Otherwise we'll get out of sync there.

**Comment by yselkowitz** [comment]
Done: https://github.com/metal3-io/ironic-image/pull/320

**Comment by yselkowitz** [comment]
https://github.com/metal3-io/ironic-image/pull/320 was merged.

**Comment by dtantsur** [comment]
As you wish, we can pull it later.

**Comment by elfosardo** [comment]
/lgtm
let's merge this and the refactor as a separate change, it's more clear

**Pull request merged**
