### PR TITLE
Correct version for sushy-oem-idrac for OCP 4.11

### PR DESCRIPTION
**Pull request by elfosardo**

### CODE REVIEW

**Comment by dtantsur** [comment]
Hmm, where are the CI jobs?

**Comment by elfosardo** [comment]
> Hmm, where are the CI jobs?

@dtantsur openshift-ci bot is having a difficult time since yesterday, should be better today

**Review by iurygregory — COMMENTED** [review]
/lgtm

**Comment by elfosardo** [comment]
/lgtm
openshift-ci bot was dead, approving based on @iurygregory approval

**Comment by elfosardo** [comment]
@openshift-bot 

> @elfosardo: you cannot LGTM your own PR.

oh so now you answer :)

**Pull request merged**
