### PR TITLE
[4.16] Move ironic user and group

### PR DESCRIPTION
**Pull request by snehring**
It looks like the ironic uid / perm manipulation got included in the cachito specific section by mistake.

### CODE REVIEW

**Comment by snehring** [comment]
Was able to test this on one of the clusters I'd noticed the problem on and it seems to fix the issue.

**Comment by elfosardo** [comment]
/hold
what's the reason behind this change?

**Comment by snehring** [comment]
> /hold what's the reason behind this change?

https://github.com/okd-project/okd/issues/2030 on baremetal okd clusters the metal3 pod never comes up fully because the ironic-inspector container crashes due to the fact that the uid and gid of ironic in the container differs from the uid and gid in the container spec. This is because the customization of the uid and gid is currently only happening in ocp builds.

**Comment by snehring** [comment]
This is only relevant for 4.16, ironic uid customizations were removed entirely in https://github.com/openshift/cluster-baremetal-operator/pull/430

**Comment by elfosardo** [comment]
@snehring the assignment of UID and GID for OKD is done by the RPMs, OKD builds do not use cachito logic
I think you'll have to check the RPMs specs and see what's happening there

**Comment by snehring** [comment]
@elfosardo yes that is the behavior without this. Unfortunately they differ from the uids specified by the ironic-inspector container spec leading to a permissions issue in the container. Either the uids need to be changed here in the image or the uids need to change in the container spec in the baremetal operator.

**Comment by elfosardo** [comment]
@snehring if OKD requires a specific configuration, I suggest to apply it just for that, for example look at what I've done for OCP using the main-packages list file
even if the issue is present only in 4.16, the change will have to start from master and backported, and all tracked in a bug in the internal RED HAT Jira

**Comment by elfosardo** [comment]
@snehring again that's because only OCP builds use source code and not RPMs for the ironic projects
I think you have two choices, either you backport the BMO change to remove the specific IDs to 4.16, and let the RPM set that, or you add an OKD specific section to prepare-image

**Pull request closed without merging**
