### PR TITLE
Move upgrade and install logic to a script

### PR DESCRIPTION
**Pull request by elfosardo**
In the effort of cleaning the Dockerfile, we move the upgrade and
install logic to a script.

(cherry picked from commit 181746690865148f050e4f28889b63e87975e849)

### CODE REVIEW

**Comment by dtantsur** [comment]
/hold

Let's maybe merge https://github.com/openshift/ironic-image/pull/126 instead? It's a full merge, so that we have easier time on next sync.

**Comment by elfosardo** [comment]
let's merge https://github.com/openshift/ironic-image/pull/126 directly

**Pull request closed without merging**
