### PR TITLE
Bug 1975137: [4.8] Sync image with the latest ironic code

### PR DESCRIPTION
**Pull request by elfosardo**
Include some recent bugfixes from ironic upstream code, for example:

https://opendev.org/openstack/ironic/commit/48cedc067a2436f60de10bb9cdfb1e29f57928ee
https://opendev.org/openstack/ironic/commit/ff05ba063e8842e4de97f908eed5a9e90239f1a5
https://opendev.org/openstack/ironic/commit/4037ae147af3b3b9a1a2e732a6e4ea732e2f51fc

### CODE REVIEW

**Review by iurygregory — APPROVED** [review]

**Comment by elfosardo** [comment]
| /test e2e-metal-ipi
-- | --

**Comment by sdodson** [comment]
Re-validating bugzilla status after prow config updates.
/bugzilla refresh

**Comment by ecordell** [comment]
[patch-manager] :hourglass: This pull request was not picked by the patch manager for the current z-stream window and have to wait for the next window.

*skipped*

* Score: *0.20*
* Reason: *missed cutoff today, may make it tomorrow*

**NOTE**: This message was automatically generated, if you have questions please ask on #forum-release

**Comment by iurygregory** [comment]
I'm wondering if we need the retest-required like mentioned by the bot so the patch manager can pick-up the PR...

**Comment by elfosardo** [comment]
@iurygregory not really, the CI is passing correctly so no need for a retest

**Comment by ecordell** [comment]
[patch-manager] :hourglass: This pull request was not picked by the patch manager for the current z-stream window and have to wait for the next window.

*skipped*

* Score: *0.20*
* Reason: *missed cutoff today, may make it tomorrow*

**NOTE**: This message was automatically generated, if you have questions please ask on #forum-release

**Comment by ecordell** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 0.20

picked

**Pull request merged**
