### PR TITLE
Custom deploy: do not log the pull secret

### PR DESCRIPTION
**Pull request by dtantsur**

### CODE REVIEW

**Comment by sadasu** [comment]
/hold 
We want https://github.com/openshift/ironic-image/pull/190 to merge first

**Comment by dtantsur** [comment]
/hold cancel

The metal3 sync has merged.

**Comment by dtantsur** [comment]
/override ci/prow/prevalidation-e2e-metal-ipi-prevalidation
/override ci/prow/prevalidation-e2e-metal-ipi-virtualmedia-prevalidation 

The actual jobs have passed, and this file is not used in the CI anyway.

**Comment by dtantsur** [comment]
/override ci/prow/e2e-metal-ipi 
/override ci/prow/e2e-metal-ipi-virtualmedia 

Pointless retesting. This file is still not used anywhere.

**Pull request merged**
