### PR TITLE
Move ironic user and group

### PR DESCRIPTION
**Pull request by snehring**
Identical to #581 except without the ironic-inspector bits

### CODE REVIEW

**Comment by snehring** [comment]
This should pretty cleanly apply to 4.17 too

**Comment by snehring** [comment]
Not sure how to diagnose that failure.

**Comment by derekhiggins** [comment]
/test e2e-metal-ipi-bm

> Step e2e-metal-ipi-bm-baremetalds-devscripts-setup succeeded after 1h12m7s

failure not likely to be related to the PR as devscripts succeeded


Do you know if any of this is relevant to our upstream repository?  looks like its downstream specific to me 
https://github.com/metal3-io/ironic-image/blob/main/prepare-image.sh

**Comment by elfosardo** [comment]
/hold

what's the reason behind this change?

**Comment by snehring** [comment]
> /hold
> 
> what's the reason behind this change?

https://github.com/openshift/ironic-image/pull/581#issuecomment-2377221367 I assume this holds true for 4.18 still, but I admit I've not tested there personally.

**Comment by snehring** [comment]
> /test e2e-metal-ipi-bm
> 
> > Step e2e-metal-ipi-bm-baremetalds-devscripts-setup succeeded after 1h12m7s
> 
> failure not likely to be related to the PR as devscripts succeeded
> 
> Do you know if any of this is relevant to our upstream repository? looks like its downstream specific to me https://github.com/metal3-io/ironic-image/blob/main/prepare-image.sh

I believe it's downstream specific due to the customization of the uid and gid for ironic in https://github.com/openshift/cluster-baremetal-operator/pull/417

**Comment by snehring** [comment]
Which now that I look, seems to have been removed from 4.17, so this is likely only relevant for 4.16. Could have sworn I saw someone complaining about it in 4.17. I'll close this.

**Pull request closed without merging**
