### PR TITLE
Bug OCPBUGS-4225: Fix setting boot related attributes

### PR DESCRIPTION
**Pull request by rhjanders**
This commit brings the upstream OpenStack/Sushy fix for setting boot related attributes

https://review.opendev.org/c/openstack/sushy/+/865388

### CODE REVIEW

**Comment by elfosardo** [comment]
/hold
@rhjanders you should commit to master, release-4.13 is cloned from there as it's the active development branch

**Comment by rhjanders** [comment]
This needs to be re-raised against master
/close

**Pull request closed without merging**
