### PR TITLE
Sync with ironic-image metal3 2022-04-12

### PR DESCRIPTION
**Pull request by elfosardo**
also avoid unbound variables and other surprises in ironic-common
See https://github.com/metal3-io/ironic-image/pull/370

Also adding https://github.com/openshift/ironic-image/pull/263/commits/9d21eef7c7838ac97620aec64d0e125b923be589
to fix OKD image thanks to @jeffdyoung

### CODE REVIEW

**Comment by elfosardo** [comment]
/hold
need to fix rhel8.6 beta repo issue first

**Comment by dtantsur** [comment]
Looks good when ready to go.

**Comment by elfosardo** [comment]
to enable the new content we need https://github.com/openshift/release/pull/27728

**Comment by elfosardo** [comment]
we need this https://github.com/openshift/release/pull/27819 and we can retest

**Comment by elfosardo** [comment]
there is an issue with the sync of the repo, some new ironic packages are missing

**Comment by elfosardo** [comment]
/retest
"could not initialize namespace: timed out waiting for image pull secrets" really? :/

**Pull request merged**
