### PR TITLE
Bug OCPBUGS-4225: Fix setting boot related attributes

### PR DESCRIPTION
**Pull request by rhjanders**
This commit brings the upstream OpenStack/Sushy fix for setting boot related attributes

https://review.opendev.org/c/openstack/sushy/+/865388

### CODE REVIEW

**Comment by rhjanders** [comment]
Prevalidation jobs passed, tagging for production

[janders@carbon ~]$ ironic-builds list prevalidation ocp-4.13
/usr/lib/python3.10/site-packages/koji/util.py:66: DeprecationWarning: krb_login is deprecated, use gssapi_login instead
  warnings.warn(message, DeprecationWarning)
*** Listing latest tagged packages in prevalidation for ocp-4.13
*** Real tag is: rhaos-4.13-ironic-rhel-9-prevalidation
python-sushy-4.3.3-0.20221128165056.6489bd2.el9
[janders@carbon ~]$ ironic-builds tag production ocp-4.13 python-sushy-4.3.3-0.20221128165056.6489bd2.el9
/usr/lib/python3.10/site-packages/koji/util.py:66: DeprecationWarning: krb_login is deprecated, use gssapi_login instead
  warnings.warn(message, DeprecationWarning)
Validating sources...
Tagging builds...
Tagging python-sushy-4.3.3-0.20221128165056.6489bd2.el9 in rhaos-4.13-ironic-rhel-9-candidate
Watching tasks (this may be safely interrupted)...
49287425 tagBuild (noarch): free
49287425 tagBuild (noarch): free -> closed
  0 free  0 open  1 done  0 failed

49287425 tagBuild (noarch) completed successfully
Done!
[janders@carbon ~]$

**Review by hroyrh — COMMENTED** [review]
Looks good.
/lgtm

**Pull request merged**
